- name: This play provisions libvirt resources with terraform
  hosts: vm_host
  become: true
  vars_files:
    - vars/k8s_cluster.yml
  tasks:
    - name: Use TF project to ensure pool and network are defined
      community.general.terraform:
        project_path: "{{ workspace_directory.base_path }}/clusters/{{ k8s.cluster_name }}/libvirt-resources"
        variables:
          domain: "{{ k8s.network.domain }}"
          network_cidr: ' ["{{ k8s.network.network_cidr }}"]'
          cluster_name: "{{ k8s.cluster_name }}"
        force_init: true
        state: present

    - name: qemu SELinux fix for running images in different folders
      when: (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int  >= 18)
      block:
        - name: Ensure security_driver is disabled
          ansible.builtin.lineinfile:
            line: 'security_driver = "none"'
            path: /etc/libvirt/qemu.conf
            state: present

        - name: Restart libvirtd service
          ansible.builtin.service:
            name: libvirtd
            state: restarted

    - name: Configure netplan for br0
      ansible.builtin.copy:
        src: files/netplan.yaml
        dest: /etc/netplan/00-installer-config.yaml
        mode: 0644
      notify:
        - Netplan Apply

  handlers:
    - name: Netplan Apply
      ansible.builtin.command:
        cmd: netplan apply
